# Generated by Django 3.0 on 2019-12-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('age', models.IntegerField(max_length=3)),
                ('year', models.IntegerField(max_length=1)),
                ('year_of_graduation', models.IntegerField(max_length=4)),
            ],
        ),
    ]
