# Generated by Django 3.0 on 2019-12-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='student.Major'),
            preserve_default=False,
        ),
    ]
